using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Security.Cryptography;
using System.Data.SqlClient;
using SecurePasswordManager.Classes;
using System.Reflection;
using System.Security;

namespace SecurePasswordManager.Core
{
    internal class PasswordManagerController
    {
        private static string connectionString = @"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\jacobsl\OneDrive - Hansen Technologies Limited\Drive\PBA\Courses\Software Sequrity\Exam Project\PasswordManagerProject\SecurePasswordManager\Database\PasswordVault.mdf;Integrated Security=True;Connect Timeout=30";
        
        
        public static byte[] CreateHash(string input)
        {
            // Generate a salt
            const int SALT_SIZE = 24; // size in bytes
            const int HASH_SIZE = 24; // size in bytes
            const int ITERATIONS = 100000; // number of pbkdf2 iterations
            RNGCryptoServiceProvider provider = new RNGCryptoServiceProvider();
            byte[] salt = new byte[SALT_SIZE];
            provider.GetBytes(salt);

            // Generate the hash
            Rfc2898DeriveBytes pbkdf2 = new Rfc2898DeriveBytes(input, salt, ITERATIONS);
            
            return pbkdf2.GetBytes(HASH_SIZE);
        }

        

        public static bool CreateNewUser(string userNameInput, string masterPasswordInput)
        {
            // todo: sanitize inputs

            string masterPasswordHash = Convert.ToBase64String(PasswordManagerController.CreateHash(masterPasswordInput));
            using (SqlConnection cs = new SqlConnection(connectionString))
            {
                
                SqlCommand cmd = new SqlCommand("INSERT INTO MasterPassword (MasterPassword, UserName) values (@masterPasswordInput,@usernameinput)", cs);
                cmd.Parameters.AddWithValue("@usernameinput", userNameInput);
                cmd.Parameters.AddWithValue("@masterPasswordInput", masterPasswordHash);
                cs.Open();
                cmd.ExecuteNonQuery();
                cs.Close();
                return true;
                
            }
        }
        public static bool CreateNewItem(string name, string username, string password)
        {
            // todo: sanitize inputs

            // todo: encrypt data before storing it

            using (SqlConnection cs = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("INSERT INTO VaultItem (Name, UserName, Password) values (@name,@username,@password)", cs);
                cmd.Parameters.AddWithValue("@name", name);
                cmd.Parameters.AddWithValue("@username", username);
                cmd.Parameters.AddWithValue("@password", password);
                cs.Open();
                cmd.ExecuteNonQuery();
                cs.Close();
                return true;               
            }
        }

        public static List<VaultItem> GetAllItems()
        {
            // todo: refactor to only get items for specific user (given as parameter)
            // todo: sanitize input 

            // todo: decrypt item name before returning it (have a different key to decrypt name than to decrypt credentials)


            List<VaultItem> VaultItemList = new List<VaultItem>();

            using (SqlConnection cs = new SqlConnection(connectionString))
            {                
                    SqlCommand cmd = new SqlCommand("SELECT * FROM VaultItem", cs);                    
                    cs.Open();
                    SqlDataReader sqlDataReader = cmd.ExecuteReader();
                    VaultItemList = DataReaderMapToList<VaultItem>(sqlDataReader);
                    cs.Close();           
            }
            return VaultItemList;
        }

        private static List<T> DataReaderMapToList<T>(SqlDataReader sqlDataReader)
        {
            List<T> list = new List<T>();
            T obj = default(T);
            while (sqlDataReader.Read())
            {
                obj = Activator.CreateInstance<T>();
                foreach (PropertyInfo prop in obj.GetType().GetProperties())
                {
                    if (!object.Equals(sqlDataReader[prop.Name], DBNull.Value))
                    {
                        prop.SetValue(obj, sqlDataReader[prop.Name], null);
                    }
                }
                list.Add(obj);
            }
            return list;
        }

        internal static bool AuthenticateUser(string userNameInput, string masterPasswordInput)
        {
            // todo: sanitize inputs

            // todo: fix bug where login is not possible because a different hash is generated by the CreateHash() function everytime
            string masterPasswordHash = Convert.ToBase64String(PasswordManagerController.CreateHash(masterPasswordInput));
            
            List<User> AuthenticatedUser = new List<User>();
            using (SqlConnection cs = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM MasterPassword WHERE UserName = @Username AND masterPassword = @MasterPassword", cs);
                cmd.Parameters.AddWithValue("@Username", userNameInput);
                cmd.Parameters.AddWithValue("@MasterPassword", masterPasswordHash);
                cs.Open();
                SqlDataReader sqlDataReader = cmd.ExecuteReader();
                AuthenticatedUser = DataReaderMapToList<User>(sqlDataReader);
                cs.Close();

                if (AuthenticatedUser.Count > 0)
                {
                    return true;
                };
                
                return false;
                
            }
        }

        public static VaultItem GetItem(int idToRetrieve)
        {
            // todo: check/sanitize inputs

            // todo: decrypt item before returning it (decrypt name using one key and credentials using another key)

            List<VaultItem> VaultItemList = new List<VaultItem>();

            using (SqlConnection cs = new SqlConnection(connectionString))
            {
                SqlCommand cmd = new SqlCommand("SELECT * FROM VaultItem WHERE id = @id", cs);
                cmd.Parameters.AddWithValue("@id", idToRetrieve);
                cs.Open();
                SqlDataReader sqlDataReader = cmd.ExecuteReader();
                VaultItemList = DataReaderMapToList<VaultItem>(sqlDataReader);
                cs.Close();
            }
            return VaultItemList[0];            
        }
    }
}
